steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:${_IMAGE_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:latest'
      - '-f'
      - 'deployment/docker/red-team-pentester-v2/Dockerfile'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:latest'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester-v2:latest'

# Build timeout (20 minutes)
timeout: '1200s'

options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Enable concurrent builds
  substitutionOption: 'ALLOW_LOOSE'
  # Enable build logs
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: '${_PROJECT_ID}'
  _REGION: '${_REGION}'
  _REPOSITORY: '${_REPOSITORY}'
  _IMAGE_TAG: '${_IMAGE_TAG}'
