steps:
  # Build the Red Team Pentester container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-red-team-pentester'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:${_IMAGE_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:latest'
      - '-f'
      - 'deployment/docker/red-team-pentester/Dockerfile'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-red-team-pentester'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:${_IMAGE_TAG}'
    waitFor: ['build-red-team-pentester']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-red-team-pentester-latest'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:latest'
    waitFor: ['build-red-team-pentester']

  # Security scan the container image
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'scan-red-team-pentester'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔍 Scanning Red Team Pentester image for vulnerabilities..."
        gcloud artifacts docker images scan \
          ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:${_IMAGE_TAG} \
          --location=${_REGION} || echo "Scan failed, continuing..."
        echo "✅ Security scan completed"
    waitFor: ['push-red-team-pentester']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:${_IMAGE_TAG}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/red-team-pentester:latest'

# Build timeout (20 minutes)
timeout: '1200s'

options:
  # Use high-performance machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Enable concurrent builds
  substitutionOption: 'ALLOW_LOOSE'
  # Enable build logs
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AGENT_NAME: 'red-team-pentester'
  _AGENT_PATH: 'agents/red_team_pentester'
  _PROJECT_ID: 'tidy-computing-465909-i3'
  _REGION: 'us-central1'
  _REPOSITORY: 'aetherveil'
  _IMAGE_TAG: 'latest'

# Build tags for organization
tags:
  - 'aetherveil'
  - 'red-team'
  - 'security'
  - 'pentester'