{{- if .Values.security.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  podSelector:
    matchLabels:
      {{- include "aetherveil-sentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: coordinator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from agents
    - from:
        - podSelector:
            matchLabels:
              {{- include "aetherveil-sentinel.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: agent
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 50051
    # Allow ingress from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090
    # Allow ingress from ingress controllers
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Allow egress to Redis
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    # Allow egress to PostgreSQL
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    # Allow egress to DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow egress to Kubernetes API
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow egress to agents
    - to:
        - podSelector:
            matchLabels:
              {{- include "aetherveil-sentinel.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: agent
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-agents
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  podSelector:
    matchLabels:
      {{- include "aetherveil-sentinel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from coordinator
    - from:
        - podSelector:
            matchLabels:
              {{- include "aetherveil-sentinel.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: coordinator
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090
    # Allow ingress from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 9090
  egress:
    # Allow egress to coordinator
    - to:
        - podSelector:
            matchLabels:
              {{- include "aetherveil-sentinel.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: coordinator
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 50051
    # Allow egress to Redis
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    # Allow egress to DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow egress to external services (for security tools)
    - to: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 21
        - protocol: TCP
          port: 22
        - protocol: TCP
          port: 23
        - protocol: TCP
          port: 25
        - protocol: TCP
          port: 53
        - protocol: TCP
          port: 110
        - protocol: TCP
          port: 143
        - protocol: TCP
          port: 993
        - protocol: TCP
          port: 995
        - protocol: TCP
          port: 1433
        - protocol: TCP
          port: 3306
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 9200
        - protocol: TCP
          port: 27017

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-deny-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

{{- end }}