{{- if .Values.security.podSecurityStandards.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ .Values.security.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.security.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.security.podSecurityStandards.warn }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "aetherveil-sentinel.selectorLabels" . | nindent 6 }}

---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
spec:
  limits:
  - default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "100m"
    type: Container
  - max:
      memory: "4Gi"
      cpu: "2000m"
    type: Container
  - max:
      memory: "8Gi"
      cpu: "4000m"
    type: Pod

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    replicationcontrollers: "10"
    secrets: "30"
    configmaps: "30"
    services: "10"
    persistentvolumeclaims: "10"

{{- end }}