{{- range $agentType, $agent := .Values.agents }}
{{- if and $agent.enabled $agent.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "aetherveil-sentinel.fullname" $ }}-agent-{{ $agentType }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" $ | nindent 4 }}
    app.kubernetes.io/component: agent
    app.kubernetes.io/agent-type: {{ $agentType }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aetherveil-sentinel.fullname" $ }}-agent-{{ $agentType }}
  minReplicas: {{ $agent.autoscaling.minReplicas }}
  maxReplicas: {{ $agent.autoscaling.maxReplicas }}
  metrics:
    {{- if $agent.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $agent.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $agent.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $agent.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}
{{- end }}