apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-agent-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- if .Values.integrations.apis.shodan.enabled }}
  shodan-api-key: {{ .Values.integrations.apis.shodan.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.integrations.apis.virustotal.enabled }}
  virustotal-api-key: {{ .Values.integrations.apis.virustotal.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.integrations.apis.censys.enabled }}
  censys-api-key: {{ .Values.integrations.apis.censys.apiKey | b64enc }}
  censys-secret: {{ .Values.integrations.apis.censys.secret | b64enc }}
  {{- end }}