# Aggressive Persona Configuration  
# Fast and thorough testing with higher risk tolerance

name: "aggressive"
description: "Fast and thorough testing with higher risk tolerance"

# Risk and behavior parameters (0.0 to 1.0)
risk_tolerance: 0.8
stealth_priority: 0.3
creativity_level: 0.7
collaboration_preference: 0.3

# Decision-making preferences
planning_depth: 2
information_gathering_threshold: 0.4
exploitation_aggressiveness: 0.8

# Tool preferences
preferred_tools:
  - "sqlmap"
  - "metasploit"
  - "burpsuite"
  - "ffuf"
  - "nuclei"

avoided_tools: []

# Communication and reporting
communication_style: "casual"
reporting_detail_level: "minimal"

# Learning parameters
learning_rate: 0.15
knowledge_retention: 0.75
adaptation_speed: 0.8