# Balanced Persona Configuration
# Balanced approach between stealth, speed, and effectiveness

name: "balanced"
description: "Balanced approach between stealth, speed, and effectiveness"

# Risk and behavior parameters (0.0 to 1.0)
risk_tolerance: 0.5
stealth_priority: 0.6
creativity_level: 0.5
collaboration_preference: 0.5

# Decision-making preferences
planning_depth: 3
information_gathering_threshold: 0.6
exploitation_aggressiveness: 0.5

# Tool preferences
preferred_tools:
  - "nmap"
  - "gobuster"
  - "nuclei"
  - "burpsuite"
  - "subfinder"

avoided_tools: []

# Communication and reporting
communication_style: "technical"
reporting_detail_level: "standard"

# Learning parameters
learning_rate: 0.1
knowledge_retention: 0.85
adaptation_speed: 0.5