{{- if .Values.coordinator.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-coordinator-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  accessModes:
    - {{ .Values.coordinator.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.coordinator.persistence.size }}
  {{- if .Values.coordinator.persistence.storageClass }}
  {{- if (eq "-" .Values.coordinator.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.coordinator.persistence.storageClass }}
  {{- end }}
  {{- end }}
{{- end }}