apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-coordinator-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
type: Opaque
data:
  database-password: {{ .Values.postgresql.auth.password | b64enc }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  jwt-secret-key: {{ .Values.coordinator.config.security.jwtSecretKey | default "default-jwt-secret" | b64enc }}
  {{- if .Values.backup.enabled }}
  {{- if eq .Values.backup.storage.type "s3" }}
  aws-access-key-id: {{ .Values.backup.storage.awsAccessKeyId | b64enc }}
  aws-secret-access-key: {{ .Values.backup.storage.awsSecretAccessKey | b64enc }}
  {{- end }}
  {{- end }}
  {{- if .Values.integrations.slack.enabled }}
  slack-webhook: {{ .Values.integrations.slack.webhook | b64enc }}
  {{- end }}
  {{- if .Values.integrations.email.enabled }}
  email-password: {{ .Values.integrations.email.smtp.password | b64enc }}
  {{- end }}
  {{- if .Values.integrations.apis.shodan.enabled }}
  shodan-api-key: {{ .Values.integrations.apis.shodan.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.integrations.apis.virustotal.enabled }}
  virustotal-api-key: {{ .Values.integrations.apis.virustotal.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.integrations.apis.censys.enabled }}
  censys-api-key: {{ .Values.integrations.apis.censys.apiKey | b64enc }}
  censys-secret: {{ .Values.integrations.apis.censys.secret | b64enc }}
  {{- end }}