apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-coordinator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  annotations:
    {{- if .Values.monitoring.serviceMonitor.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    {{- end }}
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: {{ .Values.coordinator.service.targetPort }}
      protocol: TCP
      name: http
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "aetherveil-sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aetherveil-sentinel.fullname" . }}-coordinator-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aetherveil-sentinel.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: {{ .Values.coordinator.service.targetPort }}
      protocol: TCP
      name: http
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
  selector:
    {{- include "aetherveil-sentinel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator