apiVersion: v2
name: aetherveil-sentinel
description: A Helm chart for Aetherveil Sentinel distributed swarm system
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - security
  - penetration-testing
  - distributed-system
  - swarm
  - agents
home: https://github.com/aetherveil/sentinel
sources:
  - https://github.com/aetherveil/sentinel
maintainers:
  - name: Aetherveil Team
    email: team@aetherveil.com
dependencies:
  - name: redis
    version: "17.8.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: prometheus
    version: "15.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
annotations:
  category: Security
  license: MIT